name: Documentation

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - run: sudo apt update && sudo apt install gcc-11 g++-11
        shell: bash
      
      - name: Configure cmake for Doxygen
        run: cmake -B ${{github.workspace}}/build
        shell: bash
        env:
          CC:   gcc-11
          CXX:  g++-11

      # Testing with a different python
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.7' 
        
      # Install requirements
      # Note: doxygen is not visible in $PATH until the subsequent actions.
      - name: Install Doxygen
        run: |
          wget https://www.doxygen.nl/files/doxygen-1.9.5.linux.bin.tar.gz
          tar -xvf doxygen-1.9.5.linux.bin.tar.gz
          echo "${{github.workspace}}/doxygen-1.9.5/bin" >> $GITHUB_PATH
        shell: bash
        
      - name: Install/Verify Requirements
        run: |
          python --version
          doxygen --version
          cd ${{github.workspace}}/docs/sphinx
          pip install -r requirements.txt

      # Build Sphinx documentation
      - name: Build Documentation
        run: |
          cd ${{github.workspace}}/docs/sphinx
          make html
        
      - name: Setup Pages
        uses: actions/configure-pages@v2
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload html directory
          path: './docs/sphinx/_build/html'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
